/**
 * Robot Action Keys.
 */
enum RobotActionKeys {
    UPDATE_ROBOT_ACTION = 'UPDATE_ROBOT_ACTION',
    ROTATE_ROBOT_FACE_ACTION = 'ROTATE_ROBOT_FACE_ACTION',
    MOVE_ROBOT_UP_ACTION = 'MOVE_ROBOT_UP_ACTION',
    MOVE_ROBOT_DOWN_ACTION = 'MOVE_ROBOT_DOWN_ACTION',
    MOVE_ROBOT_LEFT_ACTION = 'MOVE_ROBOT_LEFT_ACTION',
    MOVE_ROBOT_RIGHT_ACTION = 'MOVE_ROBOT_RIGHT_ACTION',
    REPORT_ROBOT_LOCATION_ACTION = 'REPORT_ROBOT_LOCATION_ACTION',
    ERROR_ROBOT_ACTION = 'ERROR_ROBOT_ACTION'
}

export default RobotActionKeys;